# Generated by Django 3.0.5 on 2020-05-16 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_contactme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
