# Generated by Django 3.0.5 on 2020-05-09 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_blogcomment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogComment',
        ),
    ]
