# Generated by Django 3.0.5 on 2020-05-16 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
    ]
